# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- main

# later we can think of a different pool for molsys
pool: pylmps 

steps:

- script: |
    source source_me 
    cd tests/graph/comp_graph/
    python3 test.py
    python3 test_comp_graph.py
  displayName: 'testing molgraph comparison'

- script: |
    source source_me 
    cd tests/obabel/
    python3 test.py
  displayName: 'testing openbabel integration'

- script: |
    source source_me 
    cd tests/utils/adding_hydrogen/
    python3 test_add_H_to_hexane.py
  displayName: 'testing util to add hydrogen'

- script: |
    source source_me 
    cd tests/lqg/
    python3 lqg_test.py
  displayName: 'testing util to add hydrogen'
