#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert different structure file formats based on molsys
#
#########################################################################


import sys
import string
import molsys.util.unit_cell as unit_cell
import molsys.mol as mol
import molsys.util.rotations as rotations

fi = sys.argv[1]
fi_type = fi.split('.')[-1]

m = mol()
m.read(fi, ftype = fi_type)
m.addon('bb')
m.center_point = 'com'
m.bb.center()
m.xyz = rotations.align_pax(m.xyz,masses=m.get_mass())



m.write(fi, ftype = fi_type)
