#!/usr/bin/python -i
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to set the cellparams of a mfpx file ## old file is gone afterwards
#
#########################################################################


import sys
import string
import molsys.mol as mol


fi = sys.argv[1]
fi_type = fi.split('.')[-1]
m = mol()
m.read(fi, ftype = fi_type)



