#!/usr/bin/python -i

##########################################################
#
#   Script to set up a proper vmd visualization for 
#   Cu-based MOFs. In particular Cu is changed to Zn
#   because vmd's coloring thinks Cu is C and hence
#   colors it according to the C color. There is no way
#   out of this apart from changing the element beforehand
#
##########################################################

import molsys
import sys
import os
import copy

argv = copy.copy(sys.argv)
fname = sys.argv[1]
name = fname.rsplit('.',1)[0]

supercell = None; fullcell = False
if argv.count('-fullcell') != 0:
    fullcell = True

if argv.count('-scell') != 0:
    idx = argv.index('-scell')
    supercell = [int(x) for x in argv[idx+1].split(',')]
    argv.pop(idx)


m = molsys.mol.from_file(fname)
cellparams = copy.copy(m.get_cellparams())
if supercell is not None:
    m.make_supercell(supercell)
if fullcell is True:
    cellparams = copy.copy(m.get_cellparams())

frac = m.get_frac_xyz()
frac = frac % 1.0
m.set_xyz_from_frac(frac)

for i,e in enumerate(m.elems):
    if e == 'cu':
        m.elems[i] = 'zn'

m.write(name+'.pdb' ,ftype='pdb')


text = """
pbc set {%12.6f %12.6f %12.6f %12.6f %12.6f %12.6f} -all
pbc box

mol color Name
mol representation DynamicBonds 2.100000 0.150000 50.000000
mol selection all
mol material Opaque
mol addrep 0

mol color Name
mol representation VDW 0.250000 50.000000
mol selection all
mol material Opaque
mol addrep 0

color Name Z ochre
""" % (tuple(cellparams))
f = open('tmp.vmd','w')
f.write(text)
f.close()

os.system('vmd %s.pdb -e tmp.vmd' % (name))


