#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Test script to compare all structures which are different."""

import os
import pylmps
import molsys
import sys
from molsys.util import RDB


if len(sys.argv) < 3:
    print ("usage:  similar_RDB <db_path> <lot_name>")
    exit
    
db_path = sys.argv[1]
lot_name = sys.argv[2]

print ("open database %s" % db_path)
rdb = RDB.RDB(db_path)

# get all entries in opt_species
db = rdb.db
lot = rdb.get_lot(lot_name)
rows = db(db.opt_species.lotID == lot).select()

# get all the structures which are different and write them to the database
maindir = os.getcwd()
specs = []
opt_speciesID = []
for r in rows:
    specs.append(r.xyz)
    opt_speciesID.append(r.id)

similar = False
path = "%s/storage/xyz" % db_path
os.chdir(path)
unique_specs = []
for i_xyz, optspecID in zip(specs, opt_speciesID):
    similar = False
    for j_xyz, optspecJD in zip(specs, opt_speciesID):
        if i_xyz < j_xyz:
            os.system('echo "%s %s" | similaritycheck' %(i_xyz, j_xyz))
            similar = os.path.isfile('ISSIMILAR')
            if similar:
                rdb.add_similar(lot=lot, optspecID=optspecID, simoptspecID=optspecJD)
                os.remove("ISSIMILAR")
                break
    if not similar and i_xyz not in unique_specs:
        unique_specs.append(optspecID)

#print(unique_specs)
os.chdir(maindir)
