#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to translate the coordinates of an atomistic system        
#
#########################################################################


import sys
import string
import molsys.mol as mol


print('USAGE: provide [tx] or [tx ty] or [tx ty tz] as translation factors')
# TBI: print '-rel results in the use of fractional displacements'

fi = sys.argv[1]
fi_type = fi.split('.')[-1]
fo = fi #.split('.')[0]+'_'+sys.argv[2]+'.mfpx'
fo_type = fi_type

if len(sys.argv) <=2 : print('please provide a translation')

tx = float(sys.argv[2])
try:
    ty = float(sys.argv[3])
except:
    ty = 0.0
try:
    tz = float(sys.argv[4])
except:
    tz = 0.0

m = mol()
m.read(fi, ftype = fi_type)
m.translate([tx,ty,tz])
m.wrap_in_box()

m.write(fo, ftype = fo_type)
