#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert different structure file formats based on molsys
#
#########################################################################


import molsys.stow as stow
import string
import unit_cell
import molsys.mol as mol

option = [
        ['', 'i', 'ifile'],
        ['', 'o', 'ofile'],
        ['', 'if', 'iftype'],
        ['', 'of', 'oftype'],
        ['', 'c', 'cell']]

shellval = stow.main(stow.sys.argv[1:], option)

fi = shellval[0]
fo = shellval[1]
fti = shellval[2]
if fti =='':fti=string.split(fi,'.')[-1]
fto = shellval[3]
if fto =='':fto=string.split(fo,'.')[-1]
cell = shellval[4]

m = mol.mol()
m.read(fi, ftype = fti)
if cell:
    cellparams = [float(i) for i in cell.split()]
    m.set_cellparams(cellparams)
if fti == 'xyz':
    m.detect_conn(remove_duplicates = True)
m.write(fo, ftype = fto)
